def pcount(A,B):
    count=0
    for i in range(0,len(A)-len(B)+1):
        if B == A[i:i+len(B)]:
            count=count+1
    return count

def freqwords(A,B):
    frequentpat=[]
    count=[]
    for i in range(0,len(A)-B+1):
        Pattern=A[i:i+B]
        count.append(pcount(A,Pattern))
    maximum = max(count)
    for i in range(0,len(count)):
        if maximum == count[i]:
                frequentpat.append(A[i:i+B])
    frequentpat=set(frequentpat)
    frequentpat=list(frequentpat)
    for i in range(len(frequentpat)):
        print(frequentpat[i])
    
freqwords("GCGTATATCGGTCTGCAGGCGTATATCCACGCGCGGCGTATATCGCGTATATCGGTCTGCAGGGTCTGCAGGCGTATATCCACGCGCGATAAGCCCTGCGTATATCGCGTATATCGCGTATATCCTGCATCGCTGCATCGGCGTATATCGCGTATATCGGTCTGCAGGGTCTGCAGCACGCGCGATAAGCCCTATAAGCCCTGCGTATATCATAAGCCCTGCGTATATCGGTCTGCAGGCGTATATCCTGCATCGCTGCATCGATAAGCCCTATAAGCCCTCACGCGCGGCGTATATCGCGTATATCATAAGCCCTATAAGCCCTGGTCTGCAGATAAGCCCTCACGCGCGCACGCGCGATAAGCCCTGCGTATATCGCGTATATCATAAGCCCTATAAGCCCTGGTCTGCAGCTGCATCGCTGCATCGCTGCATCGATAAGCCCTCTGCATCGCTGCATCGCTGCATCGCACGCGCGATAAGCCCTATAAGCCCTATAAGCCCTCACGCGCGGGTCTGCAGGGTCTGCAGCACGCGCGGCGTATATCCACGCGCGATAAGCCCTATAAGCCCTCTGCATCGCACGCGCGCTGCATCGCTGCATCGGGTCTGCAGCACGCGCGCACGCGCGGGTCTGCAGGCGTATATCGCGTATATCGCGTATATCGCGTATATCGCGTATATCCTGCATCGCACGCGCGGGTCTGCAGGCGTATATCCACGCGCGGGTCTGCAGCTGCATCGATAAGCCCTGGTCTGCAGGCGTATATCCACGCGCGCTGCATCGCTGCATCGGGTCTGCAGATAAGCCCTGCGTATATCGGTCTGCAGCACGCGCGCACGCGCGGCGTATATCGCGTATATCCTGCATCGCTGCATCGGGTCTGCAGATAAGCCCTCACGCGCGGCGTATATCGGTCTGCAGGGTCTGCAG",13)